### ISSUE TITLE
"findDOMNode was called on an unmounted component"

### ISSUE THREAD

**Issue by notatestuser** [schovi/react-iscroll#47]
The stack trace follows:
```
Invariant Violation: findDOMNode was called on an unmounted component.
  at message(~/react/lib/reactProdInvariant.js:32:0)
  at r(~/react/lib/findDOMNode.js:54:0)
  at this(~/react-iscroll/dist/react-iscroll.js:152:0)
  at _runInitializeIScroll(~/react-iscroll/dist/react-iscroll.js:184:0)
  at this(~/raven-js/src/raven.js:278:0)
```

I'm guessing that this has something to do with the fact that initialisation is done [within a setTimeout](https://github.com/schovi/react-iscroll/blob/cb94e9fb31071a2e08e96f307848b4dfcd9170d6/src/react-iscroll.jsx#L137). Do you think we could verify that the component is mounted before this happens?

**Comment by schovi** [comment]
Fixed with https://github.com/schovi/react-iscroll/commit/7b556e3f3526a4a5c37b3eb9cc376efb225e059a

**Comment by notatestuser** [comment]
Thank you for fixing & publishing this!
